name: KBOT-CICD

on: 
  push:
    branches: 
      - develop
    tags:
      - v1.*

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
                          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test
#      - name: Docker Hub login
#        uses: docker/login-action@v2
      - name: GitHub registry login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build&Push
      #   env: 
      #     APP: "kbot"
      #     REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Publish service
        env:
          OS: linux
          ARCH: amd64
        run: make image push TARGETARCH=amd64

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV  

      - uses: mikefarah/yq@master
        with: 
          cmd: yq -i '.image.tag=strenv(VERSION) | .image.arch=strenv(TARGETARCH)' helm/values.yaml

      - run: | 
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "update version to $VERSION"
          git push
